
package ru.rt.oms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OMSOrderNotificationWebService", targetNamespace = "http://oms.rt.ru/", wsdlLocation = "file:/C:/javawork/FSOM/wildfly-apps/TehnogradToIL/src/wsdl/RTFFASYNCAPI_v01.wsdl")
public class OMSOrderNotificationWebService_Service
    extends Service
{

    private final static URL OMSORDERNOTIFICATIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException OMSORDERNOTIFICATIONWEBSERVICE_EXCEPTION;
    private final static QName OMSORDERNOTIFICATIONWEBSERVICE_QNAME = new QName("http://oms.rt.ru/", "OMSOrderNotificationWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/javawork/FSOM/wildfly-apps/TehnogradToIL/src/wsdl/RTFFASYNCAPI_v01.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OMSORDERNOTIFICATIONWEBSERVICE_WSDL_LOCATION = url;
        OMSORDERNOTIFICATIONWEBSERVICE_EXCEPTION = e;
    }

    public OMSOrderNotificationWebService_Service() {
        super(__getWsdlLocation(), OMSORDERNOTIFICATIONWEBSERVICE_QNAME);
    }

    public OMSOrderNotificationWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OMSORDERNOTIFICATIONWEBSERVICE_QNAME, features);
    }

    public OMSOrderNotificationWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, OMSORDERNOTIFICATIONWEBSERVICE_QNAME);
    }

    public OMSOrderNotificationWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OMSORDERNOTIFICATIONWEBSERVICE_QNAME, features);
    }

    public OMSOrderNotificationWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OMSOrderNotificationWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OMSOrderNotificationWebService
     */
    @WebEndpoint(name = "OMSOrderNotificationWebServicePort")
    public OMSOrderNotificationWebService getOMSOrderNotificationWebServicePort() {
        return super.getPort(new QName("http://oms.rt.ru/", "OMSOrderNotificationWebServicePort"), OMSOrderNotificationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OMSOrderNotificationWebService
     */
    @WebEndpoint(name = "OMSOrderNotificationWebServicePort")
    public OMSOrderNotificationWebService getOMSOrderNotificationWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oms.rt.ru/", "OMSOrderNotificationWebServicePort"), OMSOrderNotificationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OMSORDERNOTIFICATIONWEBSERVICE_EXCEPTION!= null) {
            throw OMSORDERNOTIFICATIONWEBSERVICE_EXCEPTION;
        }
        return OMSORDERNOTIFICATIONWEBSERVICE_WSDL_LOCATION;
    }

}
