
package ru.rt.oms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OMSOrderNotificationWebService", targetNamespace = "http://oms.rt.ru/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OMSOrderNotificationWebService {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.rt.oms.NotificationResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "orderStatusResponse", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
    public NotificationResponse notifyOrderStatus(
        @WebParam(name = "orderStatusNotification", targetNamespace = "http://oms.rt.ru/", partName = "parameters")
        OrderStatusNotification parameters)
        throws Fault
    ;

}
